In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [4]:
import warnings
warnings.filterwarnings('ignore')

In [5]:
dataset = pd.read_csv(r"C:\Users\nirma\OneDrive\Documents\MELBOURNE_HOUSE_PRICES_LESS.csv (2)\MELBOURNE_HOUSE_PRICES_LESS.csv")
dataset.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
0,Abbotsford,49 Lithgow St,3,h,1490000.0,S,Jellis,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
1,Abbotsford,59A Turner St,3,h,1220000.0,S,Marshall,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
2,Abbotsford,119B Yarra St,3,h,1420000.0,S,Nelson,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
3,Aberfeldie,68 Vida St,3,h,1515000.0,S,Barry,1/04/2017,3040,Western Metropolitan,1543,7.5,Moonee Valley City Council
4,Airport West,92 Clydesdale Rd,2,h,670000.0,S,Nelson,1/04/2017,3042,Western Metropolitan,3464,10.4,Moonee Valley City Council

In [6]:
dataset.nunique()

Suburb             380
Address          57754
Rooms               14
Type                 3
Price             3417
Method               9
SellerG            476
Date               112
Postcode           225
Regionname           8
Propertycount      368
Distance           180
CouncilArea         34
dtype: int64

In [7]:
# let's use limited columns which makes more sense for serving ourpurpose
cols_to_use = ['Suburb', 'Rooms', 'Type', 'Method', 'SellerG','Regionname', 'Propertycount',
'Distance', 'CouncilArea','Price']
dataset = dataset[cols_to_use]
dataset.head()

,Suburb,Rooms,Type,Method,SellerG,Regionname,Propertycount,Distance,CouncilArea,Price
0,Abbotsford,3,h,S,Jellis,Northern Metropolitan,4019,3.0,Yarra City Council,1490000.0
1,Abbotsford,3,h,S,Marshall,Northern Metropolitan,4019,3.0,Yarra City Council,1220000.0
2,Abbotsford,3,h,S,Nelson,Northern Metropolitan,4019,3.0,Yarra City Council,1420000.0
3,Aberfeldie,3,h,S,Barry,Western Metropolitan,1543,7.5,Moonee Valley City Council,1515000.0
4,Airport West,2,h,S,Nelson,Western Metropolitan,3464,10.4,Moonee Valley City Council,670000.0

In [11]:
dataset.shape

(63023, 10)

In [8]:
#Checking for Nan values
dataset.isna().sum()

Suburb               0
Rooms                0
Type                 0
Method               0
SellerG              0
Regionname           0
Propertycount        0
Distance             0
CouncilArea          0
Price            14590
dtype: int64

In [9]:
cols_to_fill_zero = ['Propertycount', 'Distance',]
dataset[cols_to_fill_zero] = dataset[cols_to_fill_zero].fillna(0)

In [14]:
dataset['Price'] =dataset['Price'].fillna(dataset.Price.mean())

In [15]:
dataset.dropna(inplace=True)
dataset.shape

(63023, 10)

In [16]:
dataset = pd.get_dummies(dataset, drop_first=True)
dataset.head()

,Rooms,Propertycount,Distance,Price,Suburb_Aberfeldie,Suburb_Airport West,Suburb_Albanvale,Suburb_Albert Park,Suburb_Albion,Suburb_Alphington,...,CouncilArea_Moreland City Council,CouncilArea_Murrindindi Shire Council,CouncilArea_Nillumbik Shire Council,CouncilArea_Port Phillip City Council,CouncilArea_Stonnington City Council,CouncilArea_Whitehorse City Council,CouncilArea_Whittlesea City Council,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council
0,3,4019,3.0,1490000.0,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,3,4019,3.0,1220000.0,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,3,4019,3.0,1420000.0,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,3,1543,7.5,1515000.0,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,2,3464,10.4,670000.0,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [17]:
X = dataset.drop('Price', axis=1)
y = dataset['Price']
from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(X, y,
test_size=0.3, random_state=2)

In [18]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(train_X, train_y)
reg.score(test_X, test_y)

0.45790153967565417

In [19]:
reg.score(train_X, train_y)

0.4790588860848841

In [20]:
from sklearn import linear_model
lasso_reg = linear_model.Lasso(alpha=50, max_iter=100, tol=0.1)
lasso_reg.fit(train_X, train_y)

Lasso(alpha=50, max_iter=100, tol=0.1)

In [21]:
lasso_reg.score(test_X, test_y)

0.4596844420489209

In [22]:
lasso_reg.score(train_X, train_y)

0.4733084717043544

In [23]:
from sklearn.linear_model import Ridge
ridge_reg= Ridge(alpha=50, max_iter=100, tol=0.1)
ridge_reg.fit(train_X, train_y)

Ridge(alpha=50, max_iter=100, tol=0.1)

In [24]:
ridge_reg.score(test_X, test_y)

0.45748932717710755

In [25]:
ridge_reg.score(train_X, train_y)

0.47030288667107734